### ISSUE TITLE
Determine `TYPES_POL2CAPELLA` dynamically from the config

### ISSUE THREAD

**Issue by ewuerger** [DSD-DBS/capella-polarion#32]
The config lacks configurability for the user:
```yaml
oa: # Specify below
  - OperationalCapability: # Capella Type with references
      - involved_activities # Specify workitem links
      - involved_entities
      - constraints
  - OperationalActivity: # Capella Type w/o references
      - inputs
      - outputs
  - OperationalEntity: # Custom Type maps to Entity
      - activities
  - FunctionalExchange:
      type: OperationalInteraction
      links:
        - exchange_items
```

With this new way the user can configure a mapping from the Capella type to the wanted Polarion type. Also its now more verbose to configure links.

**_This also fixes the situation with Capella reusing types for different layers.
This should happen after the refactoring. (Remove context from main)_**
