### ISSUE TITLE
Add filter handling for context-diagrams

### ISSUE THREAD

**Issue by ewuerger** [DSD-DBS/capella-polarion#64]
```
serializer:
      add_context_diagram:
        render_params:
          display_parent_relation: true
          include_inner_objects: true
        filters:
          - hide all uuids (NO_UUID)
          - functional exchange and exchange item name (FEX_EX_ITEMS)
```

Add filters.
